<?php

declare(strict_types=1);

return [
    AcMarche\ActivityManager\Providers\Filament\ActivityManagerPanelProvider::class,
    AcMarche\Ad\Providers\Filament\AdPanelProvider::class,
    AcMarche\Agent\Providers\Filament\AgentPanelProvider::class,
    AcMarche\AldermenAgenda\Providers\Filament\AldermenAgendaPanelProvider::class,
    AcMarche\App\Providers\Filament\AppPanelProvider::class,
    AcMarche\College\Providers\Filament\CollegePanelProvider::class,
    AcMarche\Conseil\Providers\Filament\ConseilPanelProvider::class,
    AcMarche\Courrier\Providers\Filament\CourrierPanelProvider::class,
    AcMarche\CpasLibrary\Providers\Filament\CpasLibraryPanelProvider::class,
    AcMarche\Document\Providers\Filament\DocumentPanelProvider::class,
    AcMarche\EmailManagement\Providers\Filament\EmailManagementPanelProvider::class,
    AcMarche\GuichetHdv\Providers\Filament\GuichetHdvPanelProvider::class,
    AcMarche\Hrm\Providers\Filament\HrmPanelProvider::class,
    AcMarche\MailingList\Providers\Filament\MailingListPanelProvider::class,
    AcMarche\MealDelivery\Providers\Filament\MealDeliveryPanelProvider::class,
    AcMarche\Mediation\Providers\Filament\MediationPanelProvider::class,
    AcMarche\Mileage\Providers\Filament\MileagePanelProvider::class,
    AcMarche\News\Providers\Filament\NewsPanelProvider::class,
    AcMarche\Offenses\Providers\Filament\OffensesPanelProvider::class,
    AcMarche\Pst\Providers\Filament\PstPanelProvider::class,
    AcMarche\Publication\Providers\Filament\PublicationPanelProvider::class,
    AcMarche\QrCode\Providers\Filament\QrCodePanelProvider::class,
    AcMarche\Security\Providers\Filament\SecurityPanelProvider::class,
    AcMarche\SportsActivities\Providers\Filament\SportsActivitiesPanelProvider::class,
    AcMarche\StreetWatch\Providers\Filament\StreetWatchPanelProvider::class,
    AcMarche\Telecommunication\Providers\Filament\TelecommunicationPanelProvider::class,
    AcMarche\WhoIsWho\Providers\Filament\WhoIsWhoPanelProvider::class,
    App\Providers\AppServiceProvider::class,
    App\Providers\Filament\AdminPanelProvider::class,
];
